#!/bin/sh
export LC_ALL=C


egrep -h -v '^[@!/[]|%' "$@" |

sed   -e 's%[|*]%%g'  -e 's%^.*//%%'  -e 's%[:/].*$%%'  -e 's%^\.%%'  -e 's% %%g' |

awk   -F . '
	BEGIN { F = FS; }
	/./ {
		x = ($9 F $8 F $7 F $6 F $5 F $4 F $3 F $2 F $1 F " " $0);
		sub(/^\.*/, "", x);
		print x;
	}' |

sort | uniq |

awk  '
	BEGIN { s = "@"; }
	{
		if (substr($1, 1, length(s)) != s) {
			printf("%40s\n", $2);
			s = $1;
		}
	}' |

cat #sort
